config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  
  resources :users, :only => [:show] do
    resources :plant_basic_data, :plant_management_slips, :material_stock_table, :gardening_diaries
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/material_stock_table_controller.rb
class MaterialStockTableController < ApplicationController
  before_action :authenticate_user! , only: [:index, :show, :new, :create, :edit, :update, :destroy]

  def index
    # @material_stock_tables = MaterialStockTable.where(user_id: params[:user_id]).paginate(page: params[:page], per_page: 10)
    @material_stock_tables = current_user.material_stock_tables.paginate(page: params[:page], per_page: 10)
  end

  def show
    @material_stock_table = MaterialStockTable.find(params[:id])
  end

  def new
    @material_stock_table = MaterialStockTable.new(user_id: params[:user_id])
  end

  def create
    @material_stock_table = MaterialStockTable.new(material_stock_table_params)
    if @material_stock_table.save
      flash[:success] = "#{@material_stock_table.material_name}の資材在庫表の作成に成功しました。"
      redirect_to user_material_stock_table_index_path
    else
      #flash[:alert] = "資材在庫表を作成できませんでした。"
      render :new
      # redirect_to new_user_material_stock_table_path(current_user), alert: "資材在庫表を作成できませんでした。"
    end
  end

  def edit
    @material_stock_table = MaterialStockTable.find(params[:id])
  end

  def update
    @material_stock_table = MaterialStockTable.find(params[:id])
    if @material_stock_table.update(material_stock_table_params)
      flash[:success] = "#{@material_stock_table.material_name}の資材在庫表を更新しました。"
      redirect_to user_material_stock_table_index_path(current_user)
    else
      flash[:danger] = "資材在庫表の更新は失敗しました。"
      redirect_to user_material_stock_table_index_path(current_user)
    end
  end

  def destroy
    @material_stock_table = MaterialStockTable.find(params[:id])
    @material_stock_table.destroy
    flash[:success] = "#{@material_stock_table.material_name}の資材在庫表を削除しました。"
    redirect_to user_material_stock_table_index_path(current_user)
  end

  private

    def material_stock_table_params
      params.require(:material_stock_table).permit(:user_id, :material_name, :material_price, :material_size, :material_quantity, :material_purchase_date, :material_purchase_location)
    end
end

app/helpers/material_stock_table_helper.rb
module MaterialStockTableHelper
end

app/views/material_stock_table/_edit.html.erb
<div class="modal-dialog modal-lg modal-dialog-centered">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title"><%= @material_stock_table.material_name %>の在庫表編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @material_stock_table, url: user_material_stock_table_path(@material_stock_table), local: true, method: :patch) do |f| %>
            
            <%= f.label :material_name, "資材名", class: "label-basic-info" %>
            <%= f.text_field :material_name, class: "form-control" %>

            <%= f.label :material_price, "価格", class: "label-basic-info" %>
            <%= f.text_field :material_price, class: "form-control" %>

            <%= f.label :material_size, "規格・サイズ", class: "label-basic-info" %>
            <%= f.text_field :material_size, class: "form-control" %>

            <%= f.label :material_quantity, "数量", class: "label-basic-info" %>
            <%= f.text_field :material_quantity, class: "form-control" %>

            <%= f.label :material_purchase_date, "購入日", class: "label-basic-info" %>
            <%= f.date_field :material_purchase_date, class: "form-control" %>

            <%= f.label :material_purchase_location, "購入場所", class: "label-basic-info" %>
            <%= f.text_field :material_purchase_location, class: "form-control" %>
           
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/material_stock_table/edil.js.erb
$("#edit").html("<%= escape_javascript(render 'edit') %>");
$("#edit").modal('show');

app/views/material_stock_table/index.html.erb
<% provide(:title, "MSTs") %>
<h1>資材在庫表　一覧</h1>

<div class="col-md-10 col-md-offset-1">
  <%= will_paginate @material_stock_tables, previous_label: '&lt 前へ', next_label: '次へ &gt' %>
  
    <div class="right">
      <%= link_to "資材在庫表新規作成", new_user_material_stock_table_path(user_id: params[:user_id]), class: "btn btn-info" %>
    </div>

    <table class="table-users table-hover">
      <tbody>
        <tr>
          <th class="center"><%= "資材名" %></th>
          <th class="center"><%= "規格・サイズ" %></th>
          <th class="center"><%= "数量" %></th>
          <th class="center"><%= "購入日" %></th>
          <th class="center"><%=  %></th>
        </tr>

      <% @material_stock_tables.each do |material_stock_table| %>
        <tr>
          <td><%= link_to material_stock_table.material_name, user_material_stock_table_path(id: material_stock_table.id) %></td>
          <td class="center"><%= material_stock_table.material_size %></td>
          <td class="center"><%= material_stock_table.material_quantity %></td>
          <td class="center"><%= l(material_stock_table.material_purchase_date, formats: :middle) if material_stock_table.material_purchase_date.present? %></td>
          <td class="center">
            <%= link_to "編集", edit_user_material_stock_table_path(id: material_stock_table.id), remote: true, class: "btn btn-success" %>
            <%= link_to "削除", user_material_stock_table_path(id: material_stock_table.id), method: :delete,
                data: { confirm: "#{material_stock_table.material_name}を削除してよろしいですか？" }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <%= will_paginate @material_stock_tables, previous_label: '&lt 前へ', next_label: '次へ &gt' %>
</div>

<div id="edit" class="modal" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/material_stock_table/new.html.erb
<% provide(:title, "New MST") %>

<h1>資材在庫表　新規作成</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @material_stock_table, url: user_material_stock_table_index_path(current_user), local: true, method: :post) do |f| %>
      <%= render "material_stock_table/shared/error_messages", object: @material_stock_table %>

      <%= f.hidden_field :user_id, value: current_user.id %>

      <%= f.label :material_name, "資材名", class: "label-login" %>
      <%= f.text_field :material_name, class: 'form-control' %>

      <%= f.label :material_price, "価格", class: "label-login" %>
      <%= f.text_field :material_price, class: 'form-control' %>

      <%= f.label :material_size, "規格・サイズ", class: "label-login" %>
      <%= f.text_field :material_size, class: 'form-control' %>

      <%= f.label :material_quantity, "数量", class: "label-login" %>
      <%= f.text_field :material_quantity, class: 'form-control' %>

      <%= f.label :material_purchase_date, "購入日", class: "label-login" %>
      <%= f.date_field :material_purchase_date, class: 'form-control' %>

      <%= f.label :material_purchase_location, "購入場所", class: "label-login" %>
      <%= f.text_field :material_purchase_location, class: 'form-control' %>

      <%= f.submit "新規作成", class: "btn btn-primary btn-block btn-login" %>
    <% end %>
  </div>
</div>

app/views/material_stock_table/show.html.erb
<% provide(:title, @material_stock_table.material_name) %>

<h1><%= @material_stock_table.material_name %>　在庫表</h1>

<div>
  <table class="info-table-radius">
    <tbody>
      <tr>
        <th><h2>資材名</h2></th>
        <td><h2><%= @material_stock_table.material_name %></h2></td>
      </tr>
      <tr>
        <th><h2>価格</h2></th>
        <td><h2><%= @material_stock_table.material_price %></h2></td>
      </tr>
      <tr>
        <th><h2>規格・サイズ</h2></th>
        <td><h2><%= @material_stock_table.material_size %></h2></td>
      </tr>
      <tr>
        <th><h2>数量</h2></th>
        <td><h2><%= @material_stock_table.material_quantity %></h2></td>
      </tr>
      <tr>
        <th><h2>購入日</h2></th>
        <td><h2><%= l(@material_stock_table.material_purchase_date, formats: :short) if @material_stock_table.material_purchase_date.present? %></h2></td>
      </tr>
      <tr>
        <th><h2>購入場所</h2></th>
        <td><h2><%= @material_stock_table.material_purchase_location %></h2></td>
      </tr>
    </tbody>
  </table>
</div>