config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  
  resources :users, :only => [:show] do
    resources :plant_basic_data, :plant_management_slips, :material_stock_table, :gardening_diaries
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/gardening_diary.rb
class GardeningDiary < ApplicationRecord
  belongs_to :user

  validates :work_name, presence: true

  def self.search(search)
    if search
      where(["work_name LIKE ?", "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/gardening_diaries_controller.rb
class GardeningDiariesController < ApplicationController
  before_action :authenticate_user! , only: [:index, :show, :new, :create, :edit, :update, :destroy]

  def index
    @user = User.find(params[:user_id])
    @city = City.find_by(location_id: @user.location_id)
    @current_weather = CurrentWeather.where(city_id: @city.id).order(updated_at: :DESC).limit(1).take
    # @gardening_diaries = current_user.gardening_diaries.order(implementation_date: :DESC).limit(10)
    @gardening_diaries = @user.gardening_diaries.order(implementation_date: :DESC).paginate(page: params[:page], per_page: 5).search(params[:search])
    if params[:search].present?
      @text = "「#{params[:search]}」の検索結果"
    else
      @text = "#{@user.name}の園芸日誌　一覧"
    end
  end

  def show
    @gardening_diary = GardeningDiary.find(params[:id])
  end

  def new
    @plant_basic_data = PlantBasicDatum.where(user_id: params[:user_id])
    # @plant_management_slips = PlantManagementSlip.where(id: @plant_basic_data.ids)
    @material_stock_table = MaterialStockTable.where(user_id: params[:user_id])
    @gardening_diary = GardeningDiary.new(user_id: params[:user_id])
  end

  def create
    @gardening_diary = GardeningDiary.new(gardening_diary_params)
    @plant_basic_datum = PlantBasicDatum.find(@gardening_diary.plant_name) unless @gardening_diary.plant_name == ""
    # @gardening_diary = @gardening_diary.update(plant_name: @plant_basic_datum.plant_name)
    if @gardening_diary.save
      @gardening_diary = @gardening_diary.update(plant_name: @plant_basic_datum.plant_name) unless @gardening_diary.plant_name == ""
      flash[:success] = "#{@gardening_diary.work_name}の園芸日誌の作成に成功しました。"
      redirect_to user_gardening_diaries_path
    else
      @plant_basic_data = PlantBasicDatum.where(user_id: params[:user_id])
      @material_stock_table = MaterialStockTable.where(user_id: params[:user_id])
      render :new
      # redirect_to new_user_gardening_diary_path(current_user), alert: "園芸日誌を作成できませんでした。"
    end
  end

  def edit
    @plant_basic_data = PlantBasicDatum.where(user_id: params[:user_id])
    @material_stock_table = MaterialStockTable.where(user_id: params[:user_id])
    @gardening_diary = GardeningDiary.find(params[:id])
    @plant_management_slips = PlantManagementSlip.where(plant_basic_datum_id: @plant_basic_data.ids, plant_name: @gardening_diary.plant_name)
  end

  def update
    @gardening_diary = GardeningDiary.find(params[:id])
    # @plant_basic_datum = PlantBasicDatum.find(@gardening_diary.plant_name)
    if @gardening_diary.update(gardening_diary_params)
      # @gardening_diary.update(plant_name: @plant_basic_datum.plant_name)
      flash[:success] = "#{@gardening_diary.work_name}の園芸日誌を更新しました。"
      redirect_to user_gardening_diaries_path(current_user)
    else
      flash[:danger] = "園芸日誌の更新は失敗しました。"
      redirect_to user_gardening_diaries_path(current_user)
    end
  end

  def destroy
    @gardening_diary = GardeningDiary.find(params[:id])
    @gardening_diary.destroy
    flash[:success] = "#{@gardening_diary.work_name}の園芸日誌を削除しました。"
    redirect_to user_gardening_diaries_path(current_user)
  end

  def search
  end

  private

    def gardening_diary_params
      params.require(:gardening_diary).permit(:user_id, :work_name, :implementation_date, :work_content, :plant_name, :plant_basic_datum_id, :plant_individual_name, :material_name, :material_consumption)
    end
end

app/helpers/gardening_diaries_helper.rb
module GardeningDiariesHelper
end

app/views/gardening_diaries/_edit.html.erb
<div class="modal-dialog modal-lg modal-dialog-centered">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title"><%= @gardening_diary.work_name %>の日誌編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @gardening_diary, url: user_gardening_diary_path(@gardening_diary), local: true, method: :patch) do |f| %>
            
            <%= f.label :work_name, "作業名", class: "label-basic-info" %>
            <%= f.text_field :work_name, class: "form-control" %>

            <%= f.label :implementation_date, "実施日", class: "label-basic-info" %>
            <%= f.date_field :implementation_date, class: "form-control" %>

            <%= f.label :work_content, "作業内容", class: "label-basic-info" %>
            <%= f.text_field :work_content, class: "form-control" %>

            <%= f.label :plant_name, "植物名", class: "label-basic-info" %>
            <%= f.collection_select(:plant_name, @plant_basic_data, :plant_name, :plant_name, {:include_blank => "植物名を選択してください"}, {class: 'form-control'}) %>

            <!-- 中カテゴリが差し込ませるポイントを指定するために追加　※１ -->
            <div id="plant_management_slip_insert_point"></div> 

            <!-- -----------EDIT時、中カテゴリーのダミー表示の切替 ※２---------------------- -->
            <div id="plant_management_slip">
              
                <% if @plant_management_slips.blank? %><!-- １ -->
                  <%= f.label :plant_individual_name, "植物個体名", class: "label-login" %>
                  <%= f.select(:plant_individual_name, [], {:include_blank => "植物個体名を選択してください"}, {class: 'form-control'}) %>
                <% else %>
                  <%= f.label :plant_individual_name, "植物個体名", class: "label-login" %><!-- ２ -->
                  <%= f.collection_select(:plant_individual_name, @plant_management_slips, :plant_individual_name, :plant_individual_name, {:include_blank => "植物名を選択してください"}, {class: 'form-control'}) %>
                <% end %>
              
            </div>

            <!-- -----------中カテゴリのtamplateを作成 ※3---------------------- -->
            <% @plant_basic_data.each do |plant_basic_datum|  %><!-- ３ -->
              <template id="plant_management_slip_<%= plant_basic_datum.plant_name %>"><!-- このidをもとに呼び出される-->
              <div id="selected_plant_management_slip">
                
                <%= f.label :plant_individual_name, "植物個体名", class: "label-login" %>
                <%= f.collection_select(:plant_individual_name, plant_basic_datum.plant_management_slips, :plant_individual_name, :plant_individual_name, {:include_blank => "植物個体名を選択してください"}, {class: 'form-control'}) %>
              
              </div>
              </template>
            <% end %>

            <%= f.label :material_name, "資材名", class: "label-basic-info" %>
            <%= f.collection_select(:material_name, @material_stock_table, :material_name, :material_name, {:include_blank => "資材名を選択してください"}, {class: 'form-control'}) %>

            <%= f.label :material_consumption, "資材消費量", class: "label-basic-info" %>
            <%= f.text_field :material_consumption, class: "form-control" %>

            <div class="center">
              <%= f.submit "更新", class: "btn btn-success btn-basic-info" %>
              <button type="button" class="btn btn-default btn-basic-info" data-dismiss="modal">
                キャンセル
              </button>
            </div>
           
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- javascriptの読み込み -->
<%= javascript_pack_tag 'category_select_box' %>

app/views/gardening_diaries/edit.js.erb
$("#edit").html("<%= escape_javascript(render 'edit') %>");
$("#edit").modal('show');

app/views/gardening_diaries/index.html.erb
<% provide(:title, "GDs") %>
<!--<h1><%= @user.name %>の園芸日誌　一覧</h1>-->
<h1><%= @text %></h1>

<div class="col-md-10 col-md-offset-1">

  <div class="flexcontainer">
    <table class="table-radius">
      <tbody>
        <tr>
          <% if @current_weather.weather_main == "FALSE" %>
            <th><h1><%= @user.name %>の天気情報はありません</h1></th>
          <% else %>
            <th><h1><%= @city.name %>の天気<h1></th>
          <% end %>
        </tr>
        <tr>
          <td><h2><%= l(@current_weather.updated_at, format: :short) if @current_weather.updated_at.present? %></h2></td>
        </tr>
        <tr>
          <td><%= image_tag "http://openweathermap.org/img/wn/#{@current_weather.weather_icon.chop}d@2x.png" %></td>
        </tr>
        <tr>
          <td><h2><%= @current_weather.weather_description %></h2></td>
        </tr>
        <tr>
          <td><h2><%= @current_weather.temp %>℃</h2></td>
        </tr>
        <tr>
          <td><h2>湿度　<%= @current_weather.humidity %>％</h2></td>
        </tr>
        <tr>
          <td><h2><%= @current_weather.pressure %>hPa</h2></td>
        </tr>
      </tbody>
    </table>

    <table>
      <tr>
        <td class="center"><%= link_to "園芸日誌新規作成", new_user_gardening_diary_path(user_id: params[:user_id]), data: {"turbolinks" => false}, class: "btn btn-info" %></td>
      </tr>
      <tr>
        <td>
          <h2 class="searchtext">作業名検索（あいまい検索）</h2>
            <%= form_tag(user_gardening_diaries_path, :method => 'get' ) do %>
              <%= text_field_tag 'search', '', class: "textlines", placeholder: '作業名を入力してください' %>
              <%= submit_tag '検索', :work_name => nil, class: "btn btn-success" %>
            <% end %>
        </td>
      </tr>
    </table>
  </div>

  <%= will_paginate @gardening_diaries, previous_label: '&lt 前へ', next_label: '次へ &gt' %>
    <div>
      <table class="table-users table-hover" >
        <tbody>
          <tr>
            <th class="center"><%= "作業名" %></th>
            <th class="center"><%= "実施日" %></th>
            <th class="center"><%= "植物名" %></th>
            <th class="center"><%= "資材名" %></th>
            <th class="center"><%= %></th>            
          </tr>

        <% @gardening_diaries.each do |gardening_diary| %>
          <tr>
            <td><%= link_to gardening_diary.work_name, user_gardening_diary_path(id: gardening_diary.id) %></td>
            <td><%= l(gardening_diary.implementation_date, formats: :middle) if gardening_diary.implementation_date.present? %></td>
            <td class="center"><%= gardening_diary.plant_name %></td>
            <td class="center"><%= gardening_diary.material_name %></td>
            <td class="center">
              <%= link_to "編集", edit_user_gardening_diary_path(id: gardening_diary.id), remote: true, class: "btn btn-success", data: {"turbolinks"=>false} %>
              <%= link_to "削除", user_gardening_diary_path(id: gardening_diary.id), method: :delete,
                  data: { confirm: "#{gardening_diary.work_name}を削除してよろしいですか？" }, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  <%= will_paginate @gardening_diaries, previous_label: '&lt 前へ', next_label: '次へ &gt' %>

</div>
<!-- javascriptの読み込み -->
<%= javascript_pack_tag 'category_select_box' %>
<div id="edit" class="modal" tabindex="-1" role="dialog" aria-hidden="true" ></div>

app/views/gardening_diaries/new.html.erb
<% provide(:title, "New GD") %>

<h1>園芸日誌　新規作成</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @gardening_diary, url: user_gardening_diaries_path(current_user), local: true, method: :post) do |f| %>
      <%= render "gardening_diaries/shared/error_messages", object: @gardening_diary %>

      <%= f.hidden_field :user_id, value: current_user.id %>

      <%= f.label :work_name, "作業名", class: "label-login" %>
      <%= f.text_field :work_name, class: 'form-control' %>

      <%= f.label :implementation_date, "実施日", class: "label-login" %>
      <%= f.date_field :implementation_date, class: 'form-control' %>

      <%= f.label :work_content, "作業内容", class: "label-login" %>
      <%= f.text_field :work_content, class: 'form-control' %>

      <%= f.label :plant_name, "植物名", class: "label-login" %>
      <%= f.collection_select(:plant_name, @plant_basic_data, :id, :plant_name, {:include_blank => "植物名を選択してください"}, {class: 'form-control'}) %>
      
      <%#= f.label :plant_individual_name, "植物個体名", class: "label-login" %>
      
      <!-- 中カテゴリが差し込ませるポイントを指定するために追加　※１ -->
      <div id="plant_management_slip_insert_point"></div> 

      <!-- -----------EDIT時、中カテゴリーのダミー表示の切替 ※２---------------------- -->
      <div id="plant_management_slip">
        
          <% if @plant_management_slips.blank? %><!-- A -->
            <%= f.label :plant_individual_name, "植物個体名", class: "label-login" %>
            <%= f.select(:plant_individual_name, [], {:include_blank => "植物個体名を選択してください"}, {class: 'form-control'}) %>
          <% else %>
            <%= f.label :plant_individual_name, "植物個体名", class: "label-login" %><!-- B -->
            <%= f.collection_select(:plant_individual_name, @plant_management_slips, :plant_individual_name, :plant_individual_name, {:include_blank => "植物個体名を選択してください"}, {class: 'form-control'}) %>
          <% end %>
        
      </div>

      <!-- -----------中カテゴリのtamplateを作成 ※3---------------------- -->
      <% @plant_basic_data.each do |plant_basic_datum|  %>
        <template id="plant_management_slip_<%= plant_basic_datum.id %>"><!-- このidをもとに呼び出される-->
        <div id="selected_plant_management_slip">
          
          <%= f.label :plant_individual_name, "植物個体名", class: "label-login" %><!-- C -->
          <%= f.collection_select(:plant_individual_name, plant_basic_datum.plant_management_slips, :plant_individual_name, :plant_individual_name, {:include_blank => "植物個体名を選択してください"}, {class: 'form-control'}) %>
        
        </div>
        </template>
      <% end %>

      <%= f.label :material_name, "資材名", class: "label-login" %>
      <%= f.collection_select(:material_name, @material_stock_table, :material_name, :material_name, {:include_blank => "資材名を選択してください"}, {class: 'form-control'}) %>

      <%= f.label :material_consumption, "資材消費量", class: "label-login" %>
      <%= f.text_field :material_consumption, class: 'form-control' %>

      <%= f.submit "新規作成", class: "btn btn-primary btn-block btn-login" %>
    <% end %>
  </div>
</div>
<!-- javascriptの読み込み -->
<%= javascript_pack_tag 'category_select_box' %>

app/views/gardening_diaries/show.html.erb
<% provide(:title, @gardening_diary.work_name) %>

<h1><%= @gardening_diary.work_name %>　作業内容</h1>

<div>
  <table class="info-table-radius">
    <tbody>
      <tr>
        <th><h2>作業名</h2></th>
        <td><h2><%= @gardening_diary.work_name %></h2></td>
      </tr>
      <tr>
        <th><h2>実施日</h2></th>
        <td><h2><%= l(@gardening_diary.implementation_date, formats: :short) if @gardening_diary.implementation_date.present? %></h2></td>
      </tr>
      <tr>
        <th><h2>作業内容</h2></th>
        <td><h2><%= @gardening_diary.work_content %></h2></td>
      </tr>
      <tr>
        <th><h2>植物名</h2></th>
        <td><h2><%= @gardening_diary.plant_name %></h2></td>
      </tr>
      <tr>
        <th><h2>植物個体名</h2></th>
        <td><h2><%= @gardening_diary.plant_individual_name %></h2></td>
      </tr>
      <tr>
        <th><h2>資材名</h2></th>
        <td><h2><%= @gardening_diary.material_name %></h2></td>
      </tr>
      <tr>
        <th><h2>資材消費量</h2></th>
        <td><h2><%= @gardening_diary.material_consumption %></h2></td>
      </tr>
    </tbody>
  </table>
</div>