config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  
  resources :users, :only => [:show] do
    resources :plant_basic_data, :plant_management_slips, :material_stock_table, :gardening_diaries
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :plant_basic_data, dependent: :destroy
  has_many :material_stock_tables, dependent: :destroy
  has_many :gardening_diaries, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :set_cities, only: [:new, :create, :edit, :update]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  def after_update_path_for(resource)
    user_path(resource) #ここにリダイレクト先のパスを指定
  end
  
  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private

  def set_cities
    @cities = City.all
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! , only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :set_user , only: [:show]

  def show
    @material_stock_tables = MaterialStockTable.where(user_id: params[:id]).order(updated_at: :DESC).limit(5)
    @gardening_diaries = @user.gardening_diaries.order(implementation_date: :DESC).limit(5)

    @city = City.find_by(location_id: @user.location_id)
    @current_weather = CurrentWeather.new(city_id: @city.id)

    #天気API
    #リクエストを出す
    open_weather = Api::OpenWeatherMap::Request.new(@user.location_id)
    #戻り値を受け取る
    response = open_weather.request
    if @current_weather.valid?
      #APIが正常に動作した場合
      if response['cod'] == 200
        params_weather = Api::OpenWeatherMap::Request.attributes_for(response)
        @current_weather.update(params_weather)
        #flash[:notice] = "登録に成功しました"
      else
        #APIが正常に動作しない場合も料理情報は記録する
        @current_weather.update(weather_main: "FALSE")
        flash[:notice] = "天気情報の取得に失敗しました。ページを更新してください"
      end
      #redirect_to root_url
    else
      render 'new'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %>のマイページ</h1>

<div class="col-md-10 col-md-offset-1">
  <div class="flexcontainer">
    <table class="table-user-radius">
      <tbody>
        <tr>
            <th><h1><%= @user.name %>さんの登録情報<h1></th>
        </tr>

        <tr>
          <td><h2>メールアドレス　<%= @user.email %></h2></td>
        </tr>
        <tr>
          <td><h2>居住地域　<%= @city.name %></h2></td>
        </tr>
        <tr>
          <td><h2>登録日　<%= l(@user.created_at, formats: :middle) %></h2></td>
        </tr>
        <tr>
          <td><h2>最終更新日　<%= l(@user.updated_at, formats: :middle) %></h2></td>
        </tr>
      </tbody>
    </table>
    <table class="table-radius">
      <tbody>
        <tr>
          <% if @current_weather.weather_main == "FALSE" %>
            <th><%= @user.name %>の天気情報はありません</th>
          <% else %>
            <th><h1><%= @city.name %>の天気<h1></th>
          <% end %>
        </tr>

        <tr>
          <td><%= l(@current_weather.updated_at, format: :short) if @current_weather.updated_at.present? %></td>
        </tr>
        <tr>
          <td><%= image_tag "http://openweathermap.org/img/wn/#{@current_weather.weather_icon.chop}d@2x.png" %></td>
        </tr>
        <tr>
          <td><h2><%= @current_weather.weather_description %></h2></td>
        </tr>
        <tr>
          <td><h2><%= @current_weather.temp %>℃</h2></td>
        </tr>
        <tr>
          <td><h2>湿度　<%= @current_weather.humidity %>％</h2></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="flexcontainer-lower">
    <table class="table-users table-hover" style="margin-right: 1px">
      <tbody>
        <tr>
          <th class="center"><%= "資材名" %></th>
          <th class="center"><%= "規格・サイズ" %></th>
          <th class="center"><%= "数量" %></th>
          <th class="center"><%= link_to "一覧", user_material_stock_table_index_path(@user), class: "btn tn-lg btn-success" %></th>
        </tr>

      <% @material_stock_tables.each do |material_stock_table| %>
        <tr>
          <td><%= link_to material_stock_table.material_name, user_material_stock_table_path(user_id: params[:id], id: material_stock_table.id) %></td>
          <td class="center"><%= material_stock_table.material_size %></td>
          <td class="center"><%= material_stock_table.material_quantity %></td>
          <td class="center"><%=  %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <table class="table-users table-hover" >
        <tbody>
          <tr>
            <th class="center"><%= "作業名" %></th>
            <th class="center"><%= "実施日" %></th>
            <th class="center"><%= "植物名" %></th>
            <th class="center"><%= link_to "一覧", user_gardening_diaries_path(@user), class: "btn tn-lg btn-success" %></th>
          </tr>

        <% @gardening_diaries.each do |gardening_diary| %>
          <tr>
            <td><%= link_to gardening_diary.work_name, user_gardening_diary_path(user_id: params[:id], id: gardening_diary.id) %></td>
            <td><%= l(gardening_diary.implementation_date, formats: :middle) if gardening_diary.implementation_date.present? %></td>
            <td class="center"><%= gardening_diary.plant_name %></td>
            <td class="center"><%=  %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>

</div>